### ISSUE TITLE
Problem with discovery profile

### ISSUE THREAD

**Issue by muto-esol** [eProsima/Micro-XRCE-DDS-Client#115]
Is it part of the specification that the client does not stop the discovery process until the discovery timeout is passed, even when an agent was already discovered?
For example, when the 'attempts' parameter is 1000(times) and the 'period' parameter is 1000(ms),
the client will try to discover an agent for 1000 seconds. Even when an agent is discovered, uxr_discovery_agents() does not return until 1000 seconds have passed.

In version 1.0.2, when an agent is discovered and a callback function returns true, variable 'consumed'  changes to true. And the client stops the discovery process.
https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/1a113ee584000e23bf7816819f74d61432d7c807/src/c/profile/discovery/discovery.c#L69-L73
 
But since version 1.1.0, the client does not stop the discovery process until the discovery timeout is passed. Variable 'consumed' was deleted!
https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/abcef44b1cf166445f923ce7e49ef524350d9842/src/c/profile/discovery/discovery.c#L78-L82

Is this going to be fixed?

**Comment by BorjaOuterelo** [comment]
Hi, @muto-esol.

Yep, this we will look at this and see why was changed.

It makes sense to stop the discovery once the Client has an agent already without waiting the full time, as it was before, but need to look at it.

Thanks for all the feedback.
