### ISSUE TITLE
Discovery doesn't work

### ISSUE THREAD

**Issue by tieugiang91** [eProsima/Micro-XRCE-DDS-Client#195]
Environment:
MicroXRCEAgent: Raspberry Pi 4, Ubuntu 20.10
MicroXRCEClient: Discovery example on laptop, Ubuntu 20.04
Connection: Home wifi, the 2 devices could ping each other normally.
Issue: The discovery code built couldn't discover the Agent running on Raspberry Pi, the Discovery runs for some seconds without giving any outputs. The Agent side shows no connection established.

As far as I understand, the on_agent_found callback should be invoked and show the found agent and port. However, it doesn't seem to work. Please correct me if the understanding is wrong, thank you.

**Comment by pablogs9** [comment]
How are you launching the Micro XRCE-DDS Agent? Could you share the command?

**Comment by tieugiang91** [comment]
I launched it with the command:
./MicroXRCEAgent
then
udp4 --port 2020
The other clients on ESP8266 could connect to that Agent using fixed IP and port.

**Comment by pablogs9** [comment]
To enable discovery you should use `./MicroXRCEAgent upd4 --port 2020 -d`

**Comment by tieugiang91** [comment]
Thank you for the support, the client discovered the agent.
