### ISSUE TITLE
Run session less then a millisecond

### ISSUE THREAD

**Issue by amfern** [eProsima/Micro-XRCE-DDS-Client#211]
My needs require the session to run fast, less then 1 millisecond as to not inhibit latency to the rest of the system.
But the smallest time the client can run is 1ms because it uses uxr_millis() everywhere to measure timeout,
Is there a reason why it can't be in microseconds or nanoseconds?

**Comment by pablogs9** [comment]
I think that there is no reason for having a minimum timeout of milliseconds instead of nanoseconds. Does https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/212 solve your issue?

**Comment by amfern** [comment]
Yes, it does solve it for my use case, i think using nanos to measure time can be nice, and will allow more flexibility.
