### ISSUE TITLE
Performance using UCLIENT_PROFILE_MULTITHREAD

### ISSUE THREAD

**Issue by ted-miller** [eProsima/Micro-XRCE-DDS-Client#311]
Micro-XRCE-DDS-Client: v2.1.0
Platform: Yaskawa Motoman YRC1000

I am running into an issue with performance when using multiple threads to publish concurrently. Have you guys done any performance benchmarks comparing single-threaded and multi-threaded communication?

I've got one task that is running an executor. It has a timer to publish a bunch of topics (joint_states, tf, etc), and also contains an action server (FollowJointTrajectory). With only that task is publishing, the executor works great. The timer triggers the publishers at a nice consistent interval of 40 ms. 

However, when I receive an action goal, I start another task to publish the action-feedback messages. When this task sends a feedback message at the same time as one of the other publishers, the tasks "lock up" for about 1 second. I have traced it down to the [uxr_lock function in multithread.c](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/bdaddba40a7c63bc06768196fb6919512a8759e1/src/c/profile/multithread/multithread.c#L27). 

I am using a [recursive mutex semaphore](https://www.ee.ryerson.ca/~courses/ee8205/Data-Sheets/Tornado-VxWorks/vxworks/ref/semMLib.html#top) for the lock. I can see that one task is sitting inside `uxr_lock` until the other task calls `uxr_unlock`. So, it appears that the lock is working to protect data from multiple threads (as intended), but it's causing my publish rates to plummet.

So, I'm wondering if this is the expected behavior. Is there something I can do to improve upon this? Or do I need to rethink my approach to get all communication onto the same thread? (Or implement my own lock to prevent concurrent calls to `publish`. ) If you've got some benchmark data from your own testing, I'd be interested to see it.

Thanks!

**Comment by pablogs9** [comment]
Hello @ted-miller, this second seems to be related to the time that the micro-ROS RWM waits for confirmation from the agent when it publishes a topic.

In summary, when the micro-ROS RMW publishes a reliable topic it waits for `RMW_UXRCE_PUBLISH_RELIABLE_TIMEOUT` milliseconds to retrieve the ACKNACK from the micro-ROS Agent. We can see the action feedback publishing in the same way. This `RMW_UXRCE_PUBLISH_RELIABLE_TIMEOUT` is 1000 by default.

So this can be:
- Some kind of interlock
- A lack of confirmation from the agent side

Some ideas:
- If you compile micro-ROS with `RMW_UXRCE_PUBLISH_RELIABLE_TIMEOUT` set to 500 does the lock time is reduced?
- You also can use the [Timing APIs](https://github.com/micro-ROS/rmw_microxrcedds/blob/a17896c16f86b925cd3ff9e5d6b7ccdda9824a09/rmw_microxrcedds_c/include/rmw_microros/timing.h#L44) for setting this timeout at runtime.
- What happens if you set the publisher to best effort?
- Which transport are you using?
- **Can you share your micro-ROS application so we can reproduce the issue?**

**Comment by gavanderhoorn** [comment]
I would be interested to know *why* the Agent takes so long to ack the reliable transmission.

My assumption would be that should not be necessary, and perhaps points to something we're doing incorrectly, or something we've configured incorrectly.

**Comment by pablogs9** [comment]
I'll wait for a reproducible use case.

**Comment by gavanderhoorn** [comment]
I was not implying this was a task for you @pablogs9. Just made a 'mental note'.

**Comment by ted-miller** [comment]
I'm not entirely confident that this code is reproducing the issue exactly. But, the symptom is similar enough that I'm hoping to blame the difference on the platform differences.
(The 'difference' being the frequency of occurrence and the amount of time that the thread is blocked.)

I modified the `complex_msg_publisher` application from `micro-ROS-demos/rclc`. The main function creates a node and then starts a thread. That thread will create 3 publishers that publish in an infinite loop, with 10 ms between publishes. The main thread waits 6 seconds and then creates a single publisher with 20 ms between publishes.

(BTW: Semi-off-topic... If you attempt to create publishers at the same time on different threads, they will fail. This is the reason for the 6 second delay. The number 6 was an arbitrary choice; I did not measure.)

Before and after each publish, I broadcast a UDP text message. I am measuring execution time by monitoring the broadcast messages.
- Open the wireshark capture
- Add a display column for data.text
- Set filter to `data contains "Thread 1"`
- Change Time Display format to `Seconds since previously displayed packet`
- Scroll through the list looking for abnormally large numbers
- Repeat with filter `data contains "Thread 2"`

The attached capture was started at an arbitrary point after starting the demo application. The first anomaly occurs between packet 56 - 124. On "Thread 1", the publish routine takes nearly half a second.

[multithread publisher.zip](https://github.com/eProsima/Micro-XRCE-DDS-Client/files/8111904/multithread.publisher.zip)

**Comment by pablogs9** [comment]
Hello, regarding the multithread entity creation: it is not safe to create entities concurrently as stated [in the API documentation](https://github.com/ros2/rclc/blob/dab5792f780ce2bcddae242966af877605822518/rclc/include/rclc/publisher.h#L38).

@Acuadros95 can you reproduce this issue?

**Comment by gavanderhoorn** [comment]
thanks @Acuadros95, we can try with post `v2.1.0`.

btw:

> * You can also check the publish rate with ros2 commands: `ros2 topic hz`

`ros2 topic hz` is *really* inconsistent in the rates it reports.

So much so that we have multiple Q&As on ROS Answers about this, and people writing a simple node to subscribe and calculate the message rate themselves.

**Comment by gavanderhoorn** [comment]
Just to clarify: you're basically suggesting to test with [develop](https://github.com/eProsima/Micro-XRCE-DDS-Client/commits/develop), correct?

**Comment by Acuadros95** [comment]
Didn't know about that
> ros2 topic hz is really inconsistent in the rates it reports.

And yes, you can use the current develop branch
> Just to clarify: you're basically suggesting to test with [develop](https://github.com/eProsima/Micro-XRCE-DDS-Client/commits/develop), correct?

**Comment by ted-miller** [comment]
> Both commits could help to solve your problem, please try again with the latest commit.

The initial testing looks good. My small test app (using my hardware) is working great with these update. 

> If the problem persist, share the agent output on debug mode (Launch with flag -v6) so we can discard problems on the Agent side.

If I run into any problems, I'll be sure to get some verbose output.

Thanks for the quick support!

**Comment by gavanderhoorn** [comment]
Just to get it clear: @ted-miller: what was the solution in the end?

Did you change everything to best-effort, or did the changes on the `develop` branch (with regular guaranteed QoS) solve the problems you were seeing?

**Comment by pablogs9** [comment]
FYI: We will release v2.1.1 incorporating those fixes to the stable version in the next weeks.

**Comment by ted-miller** [comment]
I used the changes on the develop branch with default qos to resolve the issue.

I will certainly use some best-effort publishers going forward. But, they were not used for this test.
