### ISSUE TITLE
How to get DataWriter or DataReader GUID in Fast-DDS

### ISSUE THREAD

**Issue by zhangyaothu** [eProsima/Micro-XRCE-DDS-Client#319]

**Comment by zhangyaothu** [comment]
Hi, after I create a data reader in micro-xrce-dds-client successfully, I would get samples after some data writer write the corresponding topic. But I am wondering if there is some way to get the data writer guid in the client, if I have more than one data writer publish the topic simutaneously and I want to distinguish the sample's source. Thansk very much!

**Comment by pablogs9** [comment]
Hello, there is no way of retrieving the sample's writer GUID in the client-side of the DDS-XRCE standard.
