### ISSUE TITLE
How to use the "uxr_buffer_create_requester_bin" function

### ISSUE THREAD

**Issue by GarMingLi** [eProsima/Micro-XRCE-DDS-Client#329]
A client uses the "uxr_buffer_create_replier_xml" function to create a replier. Another client uses the "uxr_buffer_create_requester_bin" function to create a requester.
The "uxr_buffer_create_requester_bin" function contains two parameters: "request_topic_name" and "reply_topic_name". If they are set to "", the entity cannot be created successfully. How to use this function to create a requester to communicate with the replier?

**Comment by pablogs9** [comment]
Well, as stated in [the documentation](https://micro-xrce-dds.docs.eprosima.com/en/latest/client_api.html#entities-bin-api), those two arguments represent the name of the pair of topics used to generate the service. They cannot be empty.

**Comment by GarMingLi** [comment]
> 
But in the example, these two parameters are empty。

**Comment by pablogs9** [comment]
Hello @GarMingLi could you point out where is this example? This should be fixed.

**Comment by GarMingLi** [comment]
> 

Hello @pablogs9 On“[On“ https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/examples/SharedMemoryReqRep/main.c ”In this link](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/examples/SharedMemoryReqRep/main.c)”In this link.
```
    // Create requester
    uxrObjectId requester_id = uxr_object_id(0x01, UXR_REQUESTER_ID);
    uxrQoS_t qos = {
        .reliability = UXR_RELIABILITY_RELIABLE, .durability = UXR_DURABILITY_TRANSIENT_LOCAL,
        .history = UXR_HISTORY_KEEP_LAST, .depth = 1
    };

    uxr_buffer_create_requester_bin(&session, output_besteffort, requester_id, participant_id, "shared_memory_reqres",
            "req_type", "res_type", "", "", qos, UXR_REPLACE);
    uxr_set_request_callback(&session, on_request, NULL);

    // Create replier
    replier_id = uxr_object_id(0x01, UXR_REPLIER_ID);
    uxr_buffer_create_replier_bin(&session, reliable_in, replier_id, participant_id, "shared_memory_reqres", "req_type",
            "res_type", "", "", qos, UXR_REPLACE);
```

**Comment by pablogs9** [comment]
You are using the shared memory feature, in this case, no topics are being created, so those strings can be empty. Have you built the library with `UCLIENT_PROFILE_SHARED_MEMORY` set to `ON`?

**Comment by GarMingLi** [comment]
> 


I am not using the "UCLIENT_PROFILE_SHARED_MEMORY" feature. I understand now, thanks! @pablogs9
