### ISSUE TITLE
Shared Memory feature with Multiple Publishers and Subscribers within MCU is not working  with Micro-XRCE-DDS-Client

### ISSUE THREAD

**Issue by ManvithRaj** [eProsima/Micro-XRCE-DDS-Client#336]
Hi @pablogs9 

I enabled shared memory flag in colcon.meta and tried shared memory example in link https://github.com/eProsima/Micro-XRCE-DDS-Client/tree/master/examples/SharedMemoryPubSub which is working without agent directly.

I just enhanced this with adding another extra publisher and subscriber but which is not working in subscribers call back.
 I have also enabled mutlithread and maxnodes  in colcon.meta as below but still not working

![image](https://user-images.githubusercontent.com/117094438/207022281-cb1ab5d1-28e0-4111-9946-9395a1776cbc.png)

Please help me in working shared memory with multiple publisher and subscribers. attaching my code here. Kept initialization, publisher and subscriber in different RTOS Tasks. which is working for single publisher and subscriber but not for multiple. please let me know if I am missing anything ?
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_system.h"

#include <uxr/client/client.h>
#include <ucdr/microcdr.h>

#include <stdio.h> //printf
#include <string.h> //strcmp
#include <stdlib.h> //atoi
#include <unistd.h>

#define BUFFER_SIZE     1024
#define HISTORY_SIZE    8

uint32_t r_counter =0 ;
uint32_t r_counter2 =0 ;
uint32_t r_index=0;
uint32_t sindex=0;
uint32_t sindex2=0;

static bool send_msg_empty(
        void* instance,
        const uint8_t* buf,
        size_t len)
{
    (void) instance;
    (void) buf;
    (void) len;

    return true;
}

static bool recv_msg_empty(
        void* instance,
        uint8_t** buf,
        size_t* len,
        int timeout)
{
    (void) instance;
    (void) buf;
    (void) len;
    (void) timeout;

    return false;
}

static bool send_msg_empty2(
        void* instance,
        const uint8_t* buf,
        size_t len)
{
    (void) instance;
    (void) buf;
    (void) len;

    return true;
}

static bool recv_msg_empty2(
        void* instance,
        uint8_t** buf,
        size_t* len,
        int timeout)
{
    (void) instance;
    (void) buf;
    (void) len;
    (void) timeout;

    return false;
}

void on_topic(
        uxrSession* session,
        uxrObjectId object_id,
        uint16_t request_id,
        uxrStreamId stream_id,
        struct ucdrBuffer* ub,
        uint16_t length,
        void* args)
{
    (void) session; (void) object_id; (void) request_id; (void) stream_id; (void) length;

    char output[255];
    r_counter++;
    ucdr_deserialize_string(ub, output, 255);

    printf("Recieved @ sub1 :: %s : %d\n", output,r_counter);
    printf("\n");
}

void on_topic2(
        uxrSession* session2,
        uxrObjectId object_id2,
        uint16_t request_id2,
        uxrStreamId stream_id2,
        struct ucdrBuffer* ub2,
        uint16_t length2,
        void* args2)
{
    (void) session2; (void) object_id2; (void) request_id2; (void) stream_id2; (void) length2;

    char output2[255];
    r_counter2++;
    ucdr_deserialize_string(ub2, output2, 255);

    printf("Recieved @ sub2 :: %s : %d\n", output2,r_counter2);
    printf("\n");
}

uxrCommunication comm;
uxrCommunication comm2;
uxrSession session;
uxrSession session2;
uxrObjectId participant_id;
uxrObjectId participant_id2;
uint8_t output_besteffort_buffer[BUFFER_SIZE];
uint8_t output_besteffort_buffer2[BUFFER_SIZE];
uint8_t input_reliable_stream_buffer[BUFFER_SIZE * HISTORY_SIZE];
uint8_t input_reliable_stream_buffer2[BUFFER_SIZE * HISTORY_SIZE];
uxrStreamId output_besteffort;
uxrStreamId output_besteffort2;
uxrStreamId reliable_in;
uxrStreamId reliable_in2;

void micro_ros_task_init(void * arg)
{
   // uint32_t count = (args == 2) ? (uint32_t)atoi(argv[1]) : 10;
   printf("Initializing Task \n");
    // Empty transport
    
    comm.send_msg = send_msg_empty;
    comm.recv_msg = recv_msg_empty;
	
    comm2.send_msg = send_msg_empty2;
    comm2.recv_msg = recv_msg_empty2;
    
    // Session
    uxr_init_session(&session, &comm, 0xAAAABBBB);
	uxr_init_session(&session2, &comm2, 0xAAAABBBB);

    // Streams
    output_besteffort =
            uxr_create_output_best_effort_stream(&session, output_besteffort_buffer, BUFFER_SIZE);			
    output_besteffort2 =
            uxr_create_output_best_effort_stream(&session2, output_besteffort_buffer2, BUFFER_SIZE);    
    reliable_in = uxr_create_input_reliable_stream(&session, input_reliable_stream_buffer, BUFFER_SIZE,
                    HISTORY_SIZE);
    reliable_in = uxr_create_input_reliable_stream(&session2, input_reliable_stream_buffer2, BUFFER_SIZE,
                    HISTORY_SIZE);

    // Create entities
    participant_id = uxr_object_id(0x01, UXR_PARTICIPANT_ID);
	participant_id2 = uxr_object_id(0x02, UXR_PARTICIPANT_ID);
    printf("Initializing done \n");

    while (1)
    { 
      vTaskDelay(10000);
    }
  	vTaskDelete(NULL);
}

uxrObjectId topic_id ;
uxrObjectId topic_id2 ;
uxrQoS_t qos = {
        .reliability = UXR_RELIABILITY_RELIABLE, .durability = UXR_DURABILITY_TRANSIENT_LOCAL,
        .history = UXR_HISTORY_KEEP_LAST, .depth = 10
    };
uxrQoS_t qos2 = {
        .reliability = UXR_RELIABILITY_RELIABLE, .durability = UXR_DURABILITY_TRANSIENT_LOCAL,
        .history = UXR_HISTORY_KEEP_LAST, .depth = 10
    };

void micro_ros_task_pub(void * arg)
{
   char message[16][20] = {"PUB1_DATA1","PUB1_DATA2","PUB1_DATA3","PUB1_DATA4","PUB1_DATA5","PUB1_DATA6","PUB1_DATA7","PUB1_DATA8","PUB1_DATA9","PUB1_DATA10","PUB1_DATA11","PUB1_DATA12","PUB1_DATA13","PUB1_DATA14","PUB1_DATA15","PUB1_DATA16"} ;   
   char message2[3][20] = {"PUB2_DATA1","PUB2_DATA2","PUB2_DATA3"} ;  
   
   // uint32_t count = (args == 2) ? (uint32_t)atoi(argv[1]) : 10;
   vTaskDelay(200);
   printf("Pub Task \n");
// Create publisher1
    topic_id = uxr_object_id(0x01, UXR_TOPIC_ID);
    uxrObjectId publisher_id = uxr_object_id(0x01, UXR_PUBLISHER_ID);
    uxrObjectId datawriter_id = uxr_object_id(0x01, UXR_DATAWRITER_ID);
	
// Create publisher2
    topic_id2 = uxr_object_id(0x02, UXR_TOPIC_ID);
    uxrObjectId publisher_id2 = uxr_object_id(0x02, UXR_PUBLISHER_ID);
    uxrObjectId datawriter_id2 = uxr_object_id(0x02, UXR_DATAWRITER_ID);

    uxr_buffer_create_topic_bin(&session, output_besteffort, topic_id, participant_id,
            "shared_memory_topic", "shared_memory_type", UXR_REPLACE);
    uxr_buffer_create_topic_bin(&session2, output_besteffort2, topic_id2, participant_id2,
            "shared_memory_topicnew", "shared_memory_typenew", UXR_REPLACE);

    uxr_buffer_create_datawriter_bin(&session, output_besteffort, datawriter_id, publisher_id, topic_id, qos,
            UXR_REPLACE);
    uxr_buffer_create_datawriter_bin(&session2, output_besteffort2, datawriter_id2, publisher_id2, topic_id2, qos,
            UXR_REPLACE);
   
    // Publish topic
    const size_t data_lenght = 255;
    ucdrBuffer ub;
    uint32_t i = 0;
    
    const size_t data_lenght2 = 255;
    ucdrBuffer ub2;
    uint32_t i2 = 0;
	
    printf("Pub Task done \n");

    while (1)
    {
        if( i< 16)
        {
           sindex = i;
        }
        else
        {
          sindex= (i % 16);
        }
        uxr_prepare_output_stream(&session, output_besteffort, datawriter_id, &ub, data_lenght);
        ucdr_serialize_string(&ub, message[sindex]);
        
        printf("Publishing @pub1 : %s :%d\n", message[sindex],i);
        i++;
		
		if( i2< 3)
        {
           sindex2 = i2;
        }
        else
        {
          sindex2= (i2 % 3);
        }
		uxr_prepare_output_stream(&session2, output_besteffort2, datawriter_id2, &ub2, data_lenght2);
        ucdr_serialize_string(&ub2, message2[sindex2]);
        
        printf("Publishing @ pub2 : %s :%d\n", message2[sindex2],i2);
        i2++;
		
		
        uxr_run_session_time(&session, 1000);
	uxr_run_session_time(&session2, 1000);
        vTaskDelay(1000);
    }

    // Delete resources
    uxr_delete_session(&session);
    uxr_delete_session(&session2);

    vTaskDelete(NULL);
}

void micro_ros_task_sub(void * arg)
{
   vTaskDelay(700);
   printf("sub1 task \n");
// Create subscriber
    uxrObjectId subscriber_id = uxr_object_id(0x01, UXR_SUBSCRIBER_ID);
    uxrObjectId datareader_id = uxr_object_id(0x01, UXR_DATAREADER_ID);
    uxr_buffer_create_datareader_bin(&session, reliable_in, datareader_id, subscriber_id, topic_id, qos, UXR_REPLACE);
	
// Create subscriber2
    uxrObjectId subscriber_id2 = uxr_object_id(0x02, UXR_SUBSCRIBER_ID);
    uxrObjectId datareader_id2 = uxr_object_id(0x02, UXR_DATAREADER_ID);
    uxr_buffer_create_datareader_bin(&session2, reliable_in2, datareader_id2, subscriber_id2, topic_id2, qos2, UXR_REPLACE);

    uxr_set_topic_callback(&session, on_topic, NULL);
    uxr_set_topic_callback(&session2, on_topic2, NULL);

   printf("sub1 task done \n");
    
    while (1)
    {
        vTaskDelay(1000);
    }

    // Delete resources
    uxr_delete_session(&session);
    uxr_delete_session(&session2);

    vTaskDelete(NULL);
}

void app_main(void)
{
#if defined(CONFIG_MICRO_ROS_ESP_NETIF_WLAN) || defined(CONFIG_MICRO_ROS_ESP_NETIF_ENET)
//    ESP_ERROR_CHECK(uros_network_interface_initialize());
#endif

    //pin micro-ros task in APP_CPU to make PRO_CPU to deal with wifi:
    xTaskCreate(micro_ros_task_init,
            "uros_task",
            CONFIG_MICRO_ROS_APP_STACK,
            NULL,
            CONFIG_MICRO_ROS_APP_TASK_PRIO,
            NULL);
			
    xTaskCreate(micro_ros_task_pub,
            "uros_task",
            CONFIG_MICRO_ROS_APP_STACK,
            NULL,
            CONFIG_MICRO_ROS_APP_TASK_PRIO,
            NULL);

   xTaskCreate(micro_ros_task_sub,
            "uros_task",
            CONFIG_MICRO_ROS_APP_STACK,
            NULL,
            CONFIG_MICRO_ROS_APP_TASK_PRIO,
            NULL);

}

**Comment by pablogs9** [comment]
You need to increase max entities for shared memory: https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/CMakeLists.txt#L70

**Comment by ManvithRaj** [comment]
hi @pablogs9 

thanks a lot of the info. 

do i have to increase it in colcon.meta or directly in cmake.txt file ?

**Comment by pablogs9** [comment]
Ideally in the colcon.meta

**Comment by ManvithRaj** [comment]
awesome its working. Thank you so much @pablogs9 

I have below 2 more queries could you please clarify ?

1. Can I have a single session with multiple subscribers and publishers in this shared memory example ?

2. I could see shared memory example is directly using uxr libraries. can I use the other examples with rcl libraries for  this shared memory ?

**Comment by ManvithRaj** [comment]
hi @pablogs9 ,

If i try to create more that 2 sessions means session3 . i am getting a exception in running.

What might be the issue. is there any other flag do i need to increase ?

could you please help on this ?

**Comment by pablogs9** [comment]
> Can I have a single session with multiple subscribers and publishers in this shared memory example ?

Yes

> I could see shared memory example is directly using uxr libraries. can I use the other examples with rcl libraries for this shared memory ?

In theory you can

> If i try to create more than 2 sessions means session3 . i am getting a exception in running.

Not sure about that, in general, is recommended to have a single session for an XRCE Client program.

**Comment by ManvithRaj** [comment]
hi @pablogs9 

thank you for the reply.

For the question single session with multiple subscribers how the call back will be distinguished 

For example call back set function is like  **uxr_set_topic_callback(&session, on_topic, NULL);**

Suppose if want to create another subscriber with call back **on_topic2** how this will be distinguished if i have same session ?

**Comment by pablogs9** [comment]
You have the XRCE object id in the callback signature that will match with the create DataReader: https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/examples/SubscribeHelloWorld/main.c#L28

**Comment by ManvithRaj** [comment]
Hi @pablogs9 

I am trying below scenorio could you please help ?

Session-1 created with Publisher and subscriber with topic_id1 configured subscribercallback1

Session-2 Created only subscriber with same topic "topic_id1" configure subscribercallback2

In this case i am getting exception during runtime .

I expecting session-2 subscriber should listen session-1 publish data but not getting why it is not working

Please let me know if anything missing ?

**Comment by ManvithRaj** [comment]
Hi @pablogs9 

Could you please help in below queries i have.

1. In this shared memory example i could see there  single session which is publishing and subscribing to itself on one topic.
How to create a single session with publishing on to topic1 and subscribed to topic2.

it seems uxr_buffer_create_topic_bin has only one topic name for both . how to create a single session for two different topics ?

**Comment by ManvithRaj** [comment]
hi @pablogs9 

could you please help on the above query ?  I am waiting for your reply.

Thank you in advance.

**Comment by pablogs9** [comment]
For creating a publisher in Topic 1 here you have your topic definition: https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/4b98d2de1d198663ed4e284939363420d980b498/examples/PublishHelloWorld/main.c#L80-L85

Same for subscriptions: https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/4b98d2de1d198663ed4e284939363420d980b498/examples/SubscribeHelloWorld/main.c#L103-L109

Finally, here you have the documentation: https://micro-xrce-dds.docs.eprosima.com/en/latest/

If you need personalized training, feature acceleration, or consultancy services please write to support@eProsima.com

**Comment by ManvithRaj** [comment]
Hi @pablogs9 

Thank you so much for the information.
