### ISSUE TITLE
How to reconnect Agent?

### ISSUE THREAD

**Issue by dongsheng-autra** [eProsima/Micro-XRCE-DDS-Client#364]
How to reconnect Agent when Agent host reboot

**Comment by pablogs9** [comment]
You can use the ping functionality on the client side to detect Agent disconnections and recreate your DDS entities.

Check for `uxr_ping` here: https://micro-xrce-dds.docs.eprosima.com/en/latest/client_api.html?highlight=ping#general-utilities
