### ISSUE TITLE
How to use SHM

### ISSUE THREAD

**Issue by ge65luz** [eProsima/Micro-XRCE-DDS-Client#366]
## Issue template

- Hardware description: docker, Ubuntu 22.04
- RTOS: 
- Installation type: 
- Version or commit hash: humble

#### Steps to reproduce the issue
Hey, i have created a publisher and subscriber chain with micro-ROS nodes in a docker container , to analyze latencies. It works fine when i use the Agent. Now i want to use SHM. Therefore, i added` "-DUCLIENT_PROFILE_SHARED_MEMORY=ON"` to my colcon.meta. Do i still have to build the agent and the other steps like:

```
ros2 run micro_ros_setup build_firmware.sh
source install/local_setup.bash
ros2 run micro_ros_setup create_agent_ws.sh
ros2 run micro_ros_setup build_agent.sh
source install/local_setup.bash
ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888 -v6

```
When i build, the Agent is always is used.  But when i am not launching the Agent, the launched nodes fail. 

I am not using a microcontroller, does this still work? I want to see how big the latency is with and without the Agent. Furthermore, I am using Cyclone DDS for the Agent,  is this maybe the problem? 

All nodes are in the same container. 

Are there any modifications I forgot to do ?

**Comment by pablogs9** [comment]
Move this to a micro-ROS repo, Cyclone DDS is not compatible with eProsima's Micro XRCE-DDS
