### ISSUE TITLE
Reconnect to Agent

### ISSUE THREAD

**Issue by dzusan** [eProsima/Micro-XRCE-DDS-Client#367]
Hello, 

I'm using this client with the Micro-XRCE-DDS-Agent and UDP transport.  When the connection goes down and then up, or the agent shuts down and starts up again, data stream is not automatically restored. Now I periodically run `uxr_ping_agent_session`, if the Agent does not responding I recreate session, all streams and topics from scratch.

Is there a native way to reconnect to the Agent?

**Comment by pablogs9** [comment]
You are taking the recommended solution

**Comment by dzusan** [comment]
Ok, thank you.

Such approach requires serious middleware on the user side.
