### ISSUE TITLE
UXR_CONFIG_CAN_TRANSPORT_MTU is not in defined by CMake

### ISSUE THREAD

**Issue by yashi** [eProsima/Micro-XRCE-DDS-Client#369]
`UXR_CONFIG_CAN_TRANSPORT_MTU`, which was introduced in 8c0a608cd84f60218a54a629ebd8e64cb2d99a4a, is not defined by `CMakeLists.txt` unlike other `*_TRANSPORT_MTU`s.  Instead it is defined in and only in `include/uxr/client/profile/transport/can/can_transport.h`

https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/include/uxr/client/profile/transport/can/can_transport.h#L32

Nothing critical. I just noticed it while reading the code.

**Comment by pablogs9** [comment]
CAN-FD MTU is fixed by standard to 64B: https://en.wikipedia.org/wiki/CAN_FD.

This is why it is not configurable.

**Comment by yashi** [comment]
Thanks!

**Comment by yashi** [comment]
might be better to rename it to `UXR_CAN_TRANSPORT_MTU` instead.

**Comment by pablogs9** [comment]
That would be nice for sure!
