### ISSUE TITLE
how to create different topic in same thead

### ISSUE THREAD

**Issue by hanyidadada** [eProsima/Micro-XRCE-DDS-Client#385]
I want to creat publisher and subscriber in one thread，but I want to subscribe 'A‘ topic and publish 'B’ topic.
But All example use the same topic. How should I do ？

**Comment by pablogs9** [comment]
Please take a look at the documentation: https://micro-xrce-dds.docs.eprosima.com/en/latest/client_api.html#entities-bin-api.

Closing as this is not an issue.
