### ISSUE TITLE
Big endianness problem [#4438]

### ISSUE THREAD

**Issue by baozeng90** [eProsima/Micro-XRCE-DDS-Client#68]
1)When I run PublishHelloWorld demo,it will use uxr_run_session_time(connected = uxr_run_session_time(&session, 1000);).my client run on MCU(TMS570)
2)uxr_run_session_time
            ---uxr_output_streams_confirmed
                          ---uxr_is_output_reliable_stream_busy  (return 1)
                                              ---uxr_seq_num_cmp(stream->last_acknown, stream->last_sent) (return -1)
                                                       --- stream->last_acknown = 33023 , stream->last_sent=128
                                            
3)It only can pub 127 topic.The teturn of uxr_is_output_reliable_stream_busy is 1

4) What's the problem? 
Can you give me some advice?

**Comment by lemunozm** [comment]
Hi @baozeng90, 

It seems to be a problem with the processor word size. Are you using the 16bits TMS570 version? Currently, we only support 32bits processor or higher.

**Comment by lemunozm** [comment]
The PR https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/71 with the solution is already merged in `master`.

Please, set the variable `CONFIG_BIG_ENDIANNESS` of the `client.config` file to `TRUE` to compile with the big endianness behavior.
