### ISSUE TITLE
About creating participant using xml string.

### ISSUE THREAD

**Issue by OpusK** [eProsima/Micro-XRCE-DDS-Client#9]
Hi,

In the current version I know that I can only create participant through mr_write_create_participant_ref().
Will you also support REPRESENTATION_AS_XML_STRING method?
And Agent only supports "default participant" for REPRESENTATION_BY_REFERENCE method.
Will you support other strings later?

**Comment by julianbermudez** [comment]
Hi @OpusK, 

Yes there is a `mr_configure_participant_xml` function which allows you create participant by XML.
It is also planning to create a customizable database for REF entities. It is expected that we launch this feature in the coming weeks.

**Comment by OpusK** [comment]
Hi, @julianbermudez,

I look forward to the update. Thank you.

**Comment by OpusK** [comment]
@julianbermudez,

Cool! Thanks for your hard works!
